config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cars
  post 'login', to: 'session#create'
  get 'logout', to: 'session#destroy'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    validates :name, presence: true

    belongs_to :dealer_ship
end

app/models/dealer_ship.rb
class DealerShip < ApplicationRecord
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :role, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :load_car, only: %i(edit update destroy)
  before_action :validate_session_admin, only: %i(new create edit update destroy)
  before_action :validate_session

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to cars_path,
                  notice: 'Car was successfully created.'
    else
      render :new
    end
  end

  def update
    if @car.update(car_params)
      redirect_to cars_path,
                  notice: 'Car was successfully updated.'
    else
      render :edit
    end
  end

  def edit; end

  def destroy
    @car.destroy
    redirect_to cars_path,
                notice: 'Site was successfully destroyed.'
  end

  def index
    @cars = Car.all
    @user = User.find(session[:user_id])
  end

  private

  def validate_session_admin
    @user = User.find(session[:user_id])
    if @user.role != 'admin'
      redirect_to '/'
      session[:user_id] = nil
    end
  end

  def validate_session
    @user = User.find(session[:user_id])
    if @user.nil?
      redirect_to '/'
      session[:user_id] = nil
    end
  end

  def load_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:name, :status, :price, :dealer_ship_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index; end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def create
        @user = User.find_by(name: params[:name])
        if @user
           session[:user_id] = @user.id
           redirect_to cars_path
        else
           redirect_to '/'
        end   
    end

    def destroy
        session[:user_id] = nil
        redirect_to '/'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/edit.html.erb
<%= form_for @car, url: car_path(@car), html: { method: :put }  do |f|%>
    <div class="column">
        <%= f.label :name, 'Car model name' %> <br/>
        <%= f.text_field :name %>
    </div>
    <div class="column">
        <%= f.label :price, 'Car price' %> <br/>
        <%= f.number_field :price %>
    </div>
    <div class="column">
        <%= f.label :status, 'Car status' %> <br/>
        <%= f.select :status, ['new', 'used'], include_blank: true %>
    </div>
    <div class="column">
        <%= f.label :dealer_ship_id, 'Car status' %> <br/>
        <%= f.select :dealer_ship_id, DealerShip.all.collect {|s| [s.name, s.id]}, include_blank: true %>
    </div>
    <%= f.submit 'Edit car', class: 'button is-primary is-rounded', style: 'padding: 0 3rem;' %>
<% end %>

app/views/cars/index.html.erb
<h1>Welcome <%= @user.name %></h1>
<table>
<% @cars.each do |car| %>
    <p>Name: <%= car.name %></p>
    <p>Status: <%= car.status %></p>
    <p>Price: <%= car.price %></p>
    <p>Dealership: <%= car.dealer_ship.name %></p>
    <% if @user.role == 'admin' %>
        <%=link_to 'Remove car', car_path(car), method: :delete %>
    <% end %>
    <br/>
    <% if @user.role == 'admin' %>
        <%=link_to 'Edit car', edit_car_path(car) %>
    <% end %>
<% end %>
<br/><br/>
<% if @user.role == 'admin' %>
    <%=link_to 'Add new car', new_car_path %>
<% end %>
<br/><br/>
<%=link_to 'Log out', 'logout' %>

app/views/cars/new.html.erb
<%= form_for @car, url: cars_path, html: { method: :post }  do |f|%>
    <div class="column">
        <%= f.label :name, 'Car model name' %> <br/>
        <%= f.text_field :name %>
    </div>
    <div class="column">
        <%= f.label :price, 'Car price' %> <br/>
        <%= f.number_field :price %>
    </div>
    <div class="column">
        <%= f.label :status, 'Car status' %> <br/>
        <%= f.select :status, ['new', 'used'], include_blank: true %>
    </div>
    <div class="column">
        <%= f.label :dealer_ship_id, 'Car status' %> <br/>
        <%= f.select :dealer_ship_id, DealerShip.all.collect {|s| [s.name, s.id]}, include_blank: true %>
    </div>
    <%= f.submit 'Save new car', class: 'button is-primary is-rounded', style: 'padding: 0 3rem;' %>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to Car Sales Inventory</h1>
<h2>The best app to find the best cars</h2>

<h1>Login</h1>
<%= form_tag '/login' do %>
   <%= label_tag :name %>
   <%= text_field_tag :name %>
   <%= submit_tag "Login"%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>